version: '3'

services:
    db:
        image: postgres:15
        container_name: joplin_db
        volumes:
            - joplindb:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: unless-stopped
        env_file:
          - .env
    app:
        image: joplin/server:${IMAGE_TAG}
        depends_on:
            - db
        ports:
            - "22300:22300"
        restart: unless-stopped
        env_file:
          - .env
        environment:

            
volumes:
  joplindb:
