version: '3'

services:
    db:
        image: postgres:15
        container_name: joplin_db
        volumes:
            - joplindb:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: unless-stopped
        env_file:
          - .env
    app:
        image: joplin/server:${IMAGE_TAG}
        depends_on:
            - db
        ports:
            - "22300:22300"
        restart: unless-stopped
        env_file:
          - .env
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.joplin.entrypoints=web"
          - "traefik.http.routers.joplin.rule=Host(`joplin.${FQDN}`)"
          - "traefik.http.middlewares.joplin-https-redirect.redirectscheme.scheme=https"
          - "traefik.http.routers.joplin.middlewares=joplin-https-redirect"
          - "traefik.http.routers.joplin-secure.entrypoints=websecure"
          - "traefik.http.routers.joplin-secure.rule=Host(`joplin.${FQDN}`)"
          - "traefik.http.routers.joplin-secure.tls=true"
          - "traefik.http.routers.joplin-secure.service=joplin"
          - "traefik.http.services.joplin.loadbalancer.server.port=22300"
          - "kop.bind.ip=192.168.25.4"


            
volumes:
  joplindb:
