version: '2.1'

services:
  protonmail-bridge:
    container_name: protonmail
    image: shenxn/protonmail-bridge:3.19.0-1
    ports:
      - 1025:25/tcp
      - 1143:143/tcp
    restart: unless-stopped
    volumes:
      - protonmail:/root
    networks:
      - email
volumes:
  protonmail:
    name: protonmail
networks:
  email:
    external: true