services:
  adguardhome:
    image: adguard/adguardhome:v0.107.51
    container_name: adguardhome
    ports:
#      - 53:53/tcp
#      - 53:53/udp
#      - 784:784/udp
#      - 853:853/tcp
#      - 3000:3000/tcp
       - 8081:80/tcp
#      - 443:443/tcp
    network_mode: "host"
    env_file:
      .env
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE}"
      - "traefik.http.routers.adguard.entrypoints=web"
      - "traefik.http.routers.adguard.rule=Host(`${APPNAME}.${FQDN}`)"
      - "traefik.http.middlewares.adguard-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.adguard.middlewares=adguard-https-redirect"
      - "traefik.http.routers.adguard-secure.entrypoints=websecure"
      - "traefik.http.routers.adguard-secure.rule=Host(`${APPNAME}.${FQDN}`)"
      - "traefik.http.routers.adguard-secure.tls=true"
      - "traefik.http.routers.adguard-secure.service=adguard"
      - "traefik.http.services.adguard.loadbalancer.server.url=${APPIP}"
      - "traefik.http.services.adguard.loadbalancer.server.port=8081"
#      - "traefik.docker.network=proxy"
      - "kop.bind.ip=${APPIP}"
      - "homepage.group=Infrastructure"
      - "homepage.name=${APPNAME}"
      - "homepage.icon=adguard-home.png"
      - "homepage.href=https://${APPNAME}.${FQDN}/"
      - "homepage.description=${APPDESC}"
      - "homepage.widget.type=adguard"
      - "homepage.widget.url=https://${APPNAME}.${FQDN}"
      - "homepage.widget.username=${ADGUARD_UN}"
      - "homepage.widget.password=${ADGUARD_PW}"
      #autokuma
      - "kuma.Infrastructure.group.name=Infrastructure"
      - "kuma.${APPNAME}.docker.name=${APPNAME}"
      - "kuma.${APPNAME}.docker.docker_container={{container_id}}"
      - "kuma.${APPNAME}.docker.parent_name=Infrastructure"
      - "kuma.${APPNAME}.docker.docker_host=1"
      - "kuma.${APPNAME}.docker.notification_names=ntfy"
    volumes:
      - adguard-work:/opt/adguardhome/work
      - ./configdir:/opt/adguardhome/conf
    restart: unless-stopped
volumes:
  adguard-work:
