services:
  adguardhome:
    image: adguard/adguardhome:v0.107.51
    container_name: adguardhome
    ports:
#      - 53:53/tcp
#      - 53:53/udp
#      - 784:784/udp
#      - 853:853/tcp
#      - 3000:3000/tcp
       - 80:80/tcp
#      - 443:443/tcp
    network_mode: "host"
    env_file:
      .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.entrypoints=web"
      - "traefik.http.routers.adguard.rule=Host(`dns2.watermelononatoothpick.com`)"
      - "traefik.http.middlewares.adguard-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.adguard.middlewares=adguard-https-redirect"
      - "traefik.http.routers.adguard-secure.entrypoints=websecure"
      - "traefik.http.routers.adguard-secure.rule=Host(`dns2.watermelononatoothpick.com`)"
      - "traefik.http.routers.adguard-secure.tls=true"
      - "traefik.http.routers.adguard-secure.service=adguard"
      - "traefik.http.services.adguard.loadbalancer.server.port=80"
#      - "traefik.docker.network=proxy"
      - "kop.bind.ip=192.168.128.249"
      - "homepage.group=Infrastructure"
      - "homepage.name=dns2"
      - "homepage.icon=adguard.png"
      - "homepage.href=https://dns2.watermelononatoothpick.com/"
      - "homepage.description=Secondary Adguard instance"
      - "homepage.widget.type=adguard"
      - "homepage.widget.url=http://192.168.128.249"
      - "homepage.widget.username=${ADGUARD_UN}"
      - "homepage.widget.password=${ADGUARD_PW}"
    volumes:
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
    restart: unless-stopped
