services:
  traefik-kop:
    image: "ghcr.io/jittering/traefik-kop:latest"
    restart: unless-stopped
    #volumes:
     # - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "REDIS_ADDR=192.168.25.4:6379"
      - "BIND_IP=192.168.25.4"
      - "DOCKER_HOST=tcp://socketproxy-traefik:2375"
    networks:
      - traefik_backend
networks:
  traefik_backend:
    external: true
    