# Simple docker-compose.yml
# You can change your port or volume location

version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.16
    container_name: uptime-kuma
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime.entrypoints=web"
      - "traefik.http.routers.uptime.rule=Host(`uptime.${FQDN}`)"
      - "traefik.http.middlewares.uptime-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.uptime.middlewares=uptime-https-redirect"
      - "traefik.http.routers.uptime-secure.entrypoints=websecure"
      - "traefik.http.routers.uptime-secure.rule=Host(`uptime.${FQDN}`)"
      - "traefik.http.routers.uptime-secure.tls=true"
      - "traefik.http.routers.uptime-secure.service=uptime"
      - "traefik.http.services.uptime.loadbalancer.server.port=3001"
      - "traefik.docker.network=proxy"
    volumes:
      - uptime-kuma-data:/app/data
    networks:
      - proxy
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always
volumes:
  uptime-kuma-data:
networks:
  proxy:
    external: true