---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/docker/

# my-docker:
#   host: 127.0.0.1
#   port: 2375

# my-docker:
#   socket: /var/run/docker.sock
dns-1:
  host: 192.168.128.3
  port: 2375
dns-2: 
  host: 192.168.128.249
  port: 2375
nas:
  host: 192.168.25.4
  port: 2375
gpuworkstation:
  host: 192.168.25.7
  port: 2375