---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/docker/

# my-docker:
#   host: 127.0.0.1
#   port: 2375

# my-docker:
#   socket: /var/run/docker.sock
pihole:
  host: 192.168.128.3
  port: 2375
gpuworkstation:
  host: 192.168.25.7
  port: 2375
localbox:
  socket: /var/run/docker.sock