---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Cloud:
    - NextCloud:
        container: nextcloud-web-1
        icon: nextcloud
        href: "{{HOMEPAGE_VAR_NEXTCLOUD_HREF}}"
        description: Nextcloud
        widget:
          type: nextcloud
          url: {{HOMEPAGE_VAR_NEXTCLOUD_URL}}
          key: {{HOMEPAGE_VAR_NEXTCLOUD_KEY}}
    - Home Assistant:
        icon: home-assistant
        href: "{{HOMEPAGE_VAR_HASS_HREF}}"
        widget:
          type: homeassistant
          url: {{HOMEPAGE_VAR_HASS_URL}}
          key: {{HOMEPAGE_VAR_HASS_KEY}}

- Media:
    - Jellyfin:
        icon: jellyfin
        href: "{{HOMEPAGE_VAR_JELLYFIN_HREF}}"
        description: Movies and Music
        server: gpuworkstation
        container: jellyfin
        widget:
          type: jellyfin
          url: {{HOMEPAGE_VAR_JELLYFIN_URL}}
          key: {{HOMEPAGE_VAR_JELLYFIN_KEY}}
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true
          enableUser: true # optional, defaults to false
          showEpisodeNumber: true # optional, defaults to false
          expandOneStreamToTwoRows: false # optional, defaults to true
    - Audiobookshelf:
        icon: audiobookshelf
        href: "{{HOMEPAGE_VAR_BOOKS_HREF}}"
        description: Audiobooks
        container: audiobookshelf-server
        showStats: true
        widget:
          type: audiobookshelf
          url: {{HOMEPAGE_VAR_BOOKS_URL}}
          key: {{HOMEPAGE_VAR_BOOKS_KEY}}
    - Paperless-NGX:
        icon: paperless-ngx
        href: "{{HOMEPAGE_VAR_PAPERLESS_HREF}}"
        container: paperless-webserver-1
        description: Document storage
        widget:
          type: paperlessngx
          url: {{HOMEPAGE_VAR_PAPERLESS_URL}}
          key: {{HOMEPAGE_VAR_PAPERLESS_KEY}}


- Infrastructure:
    - Adguard Home:
        icon: adguard-home
        server: pihole
        container: adguard
        description: Network ad block
        href: "{{HOMEPAGE_VAR_ADGUARD_HREF}}"
        widget:
          type: adguard
          url: {{HOMEPAGE_VAR_ADGUARD_URL}}
          username: {{HOMEPAGE_VAR_ADGUARD_UN}}
          password: {{HOMEPAGE_VAR_ADGUARD_PW}}
    - Traefik:
        icon: traefik
        href: "{{HOMEPAGE_VAR_TRAEFIK_HREF}}"
        description: Reverse Proxy
        container: traefik
        widget:
          type: traefik
          url: {{HOMEPAGE_VAR_TRAEFIK_URL}}
          username: {{HOMEPAGE_VAR_TRAEFIK_UN}}
          password: {{HOMEPAGE_VAR_TRAEFIK_PW}}
    - Portainer Main:
        href: "{{HOMEPAGE_VAR_PORTAINER_HREF}}"
        description: Primary Portainer instance
        icon: portainer
        container: portainer
        widget:
          type: portainer
          url: {{HOMEPAGE_VAR_PORTAINER_URL}}
          env: 2
          key: {{HOMEPAGE_VAR_PORTAINER_KEY}}
    - Portainer DNS:
        href: "{{HOMEPAGE_VAR_PORTAINER_HREF}}"
        description: Raspberry Pi running Adguard
        icon: portainer
        widget:
          type: portainer
          url: {{HOMEPAGE_VAR_PORTAINER_URL}}
          env: 3
          key: {{HOMEPAGE_VAR_PORTAINER_KEY}}
    - Portainer GPU:
        href: "{{HOMEPAGE_VAR_PORTAINER_HREF}}"
        description: Workstation running Jellyfin and other GPU services
        icon: portainer
        widget:
          type: portainer
          url: {{HOMEPAGE_VAR_PORTAINER_URL}}
          env: 4
          key: {{HOMEPAGE_VAR_PORTAINER_KEY}}

    - Authentik:
        icon: authentik
        container: authentik-server-1
        href: "{{HOMEPAGE_VAR_AUTH_HREF}}"
        description: Authentication service
        widget:
          type: authentik
          url: {{HOMEPAGE_VAR_AUTH_URL}}
          key: {{HOMEPAGE_VAR_AUTH_KEY}}
    - Gitea:
        icon: gitea
        href: "{{HOMEPAGE_VAR_GITEA_HREF}}"
        description: Git a cup of tea 
        widget:
          type: gitea
          url: {{HOMEPAGE_VAR_GITEA_URL}}
          key: {{HOMEPAGE_VAR_GITEA_KEY}}
    - PVE:
        icon: proxmox
        href: "{{HOMEPAGE_VAR_PVE_HREF}}"
        description: Proxmox Hypervisor
        widget:
          type: proxmox
          url: {{HOMEPAGE_VAR_PVE_URL}}
          username: {{HOMEPAGE_VAR_PVE_UN}}
          password: {{HOMEPAGE_VAR_PVE_PW}}