---
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - SERVERURL=${VPS} #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS=all #optional
      - LOG_CONFS=false #optional
    labels:
      - autoheal=true
    healthcheck:
      test: curl -k https://whoami.${FQDN} -v --resolve 'whoami.${FQDN}:443:10.1.10.1'
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - ./config:/config
      #- /lib/modules:/lib/modules #optional
    #ports:
    #  - 51820:51820/udp
    #networks:
    #  - proxy
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
networks:
  proxy:
    external: true